import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from './providers';

const generalSans = localFont({
  src: [
    {
      path: '../public/fonts/GeneralSans-Variable.ttf',
      weight: '200 700',
      style: 'normal',
    },
    {
      path: '../public/fonts/GeneralSans-VariableItalic.ttf',
      weight: '200 700',
      style: 'italic',
    },
  ],
  display: 'swap',
  variable: '--font-general-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${generalSans.className}`}>
      <Providers>{children}</Providers>
    </html>
  );
}
